data:extend({
	{
		type = "bool-setting",
		name = "TOPT-AllowLongHandedInserter",
		setting_type = "startup",
		default_value = true,
		order = "a",
	},
	{
		type = "bool-setting",
		name = "TOPT-UpdateSmallElectricPoleRecipe",
		setting_type = "startup",
		default_value = false,
		order = "b",
	},
	{
		type = "bool-setting",
		name = "TOPT-AllowIronChestDefaultRecipe",
		setting_type = "startup",
		default_value = false,
		order = "c",
	},
	{
		type = "bool-setting",
		name = "TOPT-AllowConstructionRobots",
		setting_type = "startup",
		default_value = true,
		order = "d",
	},
	{
		type = "bool-setting",
		name = "TOPT-AllowModularArmor",
		setting_type = "startup",
		default_value = true,
		order = "e",
	},
	{
		type = "bool-setting",
		name = "TOPT-AllowSolarEnergyProduction",
		setting_type = "startup",
		default_value = false,
		order = "f",
	},
	{
		type = "bool-setting",
		name = "TOPT-AllowAccumulatorEnergyStorage",
		setting_type = "startup",
		default_value = false,
		order = "g",
	},
	{
		type = "bool-setting",
		name = "TOPT-AllowCoalLiquefaction",
		setting_type = "startup",
		default_value = false,
		order = "h",
	},
	{
		type = "bool-setting",
		name = "TOPT-AllowSpidertron",
		setting_type = "startup",
		default_value = true,
		order = "i",
	},
	{
		type = "bool-setting",
		name = "TOPT-AllowCombatRobots",
		setting_type = "startup",
		default_value = false,
		order = "j",
	},
	{
		type = "bool-setting",
		name = "TOPT-AllowLaserTurrets",
		setting_type = "startup",
		default_value = false,
		order = "k",
	},
	{
		type = "bool-setting",
		name = "TOPT-AllowRocketLauncher",
		setting_type = "startup",
		default_value = false,
		order = "l",
	},
	{
		type = "bool-setting",
		name = "TOPT-AllowArtillery",
		setting_type = "startup",
		default_value = false,
		order = "m",
	},
	{
		type = "bool-setting",
		name = "TOPT-AllowAtomicBombs",
		setting_type = "startup",
		default_value = false,
		order = "n",
	},
})
